### ISSUE TITLE
pytorch_lightning.utilities.debugging.MisconfigurationException: 

### ISSUE THREAD

**Issue by anniQAQ** [HasnainRaz/Fast-AgingGAN#11]
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
hello, why it can not scan my gpu, i already have a gpu named [0], however it always have such error. do you have same error before? thanks a lot

**Comment by HasnainRaz** [comment]
Sounds like a cuda issue. Please make sure pytorch can see your GPU by using "torch.cuda.is_available()". If it is False, check your cuda version/pytorch version and resolve that issue before trying this repo.
