### ISSUE TITLE
Training command

### ISSUE THREAD

**Issue by harithagb** [HasnainRaz/Fast-AgingGAN#12]
The training command mentioned in README.md has an issue. 
`python preprocessing/preprocessing_utk.py --data_dir '/path/to/cacd/images' --output_dir 'path/to/save/processed/data'
`
Has to be `preprocess_utk.py`. The file is misnamed.

**Comment by HasnainRaz** [comment]
Thanks for the suggestion, I will push a fix

**Comment by HasnainRaz** [comment]
Fixed
