### ISSUE TITLE
save the final model?

### ISSUE THREAD

**Issue by scarlettliu644** [HasnainRaz/Fast-AgingGAN#16]
Hi! May I know that do we have to add codes to save the final .pth file to a file path?

**Comment by HasnainRaz** [comment]
No, pytorch lightning makes checkpoints after every epoch in the directory of this repo. If you need to change the checkpointing schedule, you can add a checkpointing callback in main.py. See here: https://pytorch-lightning.readthedocs.io/en/latest/common/weights_loading.html
