### ISSUE TITLE
Do you have a paper to introduce this network?

### ISSUE THREAD

**Issue by Adolf-K** [HasnainRaz/Fast-AgingGAN#18]
Hello, I want to know, have you published corresponding articles on your project? I want to read it to help you understand the project. thanks

**Comment by HasnainRaz** [comment]
No, this just a simple modification of existing work out there. Please refer to the "Face aging with conditional generative adversarial network" paper to understand what's happening here. The only difference here is that I'm using a smaller neural network to make it faster.
