### ISSUE TITLE
IndexError in infer.py

### ISSUE THREAD

**Issue by ahoang512** [HasnainRaz/Fast-AgingGAN#23]
File "infer.py", line 39, in main

    ax[0, i].imshow((img.squeeze().permute(1, 2, 0).numpy() + 1.0) / 2.0)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Hello, thanks for making this! I was trying to test it out with one image and am running into this error? Do you know why this may be happening?

**Comment by HasnainRaz** [comment]
Do you have only one image in the folder you are trying to infer on? If so, add a second image, or change

```python
ax[0, i]
```

To 

```python
ax[0]
```

**Comment by ahoang512** [comment]
Perfect. thank you!
