### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by scrambled2** [HasnainRaz/Fast-AgingGAN#24]
I am attempting to train it from scratch per the instructions and have everything pre-processed and ready, but when I launch main.py I get this. Any ideas?

(fast) ubuntu@chris03:/mnt/workspace/Fast-AgingGAN$ python main.py
{'domainA_dir': 'dataoutput/trainA', 'domainB_dir': 'dataoutput/trainB', 'ngf': 32, 'ndf': 32, 'n_blocks': 9, 'adv_weight': 2, 'cycle_weight': 10, 'identity_weight': 7, 'lr': 0.0001, 'weight_decay': 0.0001, 'img_size': 256, 'batch_size': 3, 'num_workers': 4, 'epochs': 100, 'gpus': [1]}
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    main()
  File "main.py", line 17, in main
    model = AgingGAN(config)
  File "/mnt/workspace/Fast-AgingGAN/gan_module.py", line 18, in __init__
    self.hparams = hparams
  File "/mnt/workspace/Fast-AgingGAN/fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by alexriedel1** [comment]
This is due to a pytorch lightning update. I made a pull request fixing this issue: https://github.com/HasnainRaz/Fast-AgingGAN/pull/25

**Comment by HasnainRaz** [comment]
Sorry for the late resolution, I stopped keeping track of these repos. #25 is merged
