### ISSUE TITLE
too many indices for array

### ISSUE THREAD

**Issue by yumfx** [HasnainRaz/Fast-AgingGAN#27]
Hello
When I execute the infer.py script, I have this message in return

  File "/net/raid3/DEEP/GITHUB/FastAging/infer.py", line 55, in main
    ax[0, i].imshow(img)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

How can I fix it please?
Thanks!

**Comment by HasnainRaz** [comment]
@yumfx Thanks for pointing this out, it was a bug, I pushed a fix.

Please pull the latest master and it should work.
