### ISSUE TITLE
about age

### ISSUE THREAD

**Issue by AIRAR-JGS** [HasnainRaz/Fast-AgingGAN#30]
Hello!

It works very well.
What can I do to make a person look younger?

Should I change the model?

**Comment by HasnainRaz** [comment]
Yes, the model is trained using the cycleGAN method, that means at the end we get two models: old to young and young to old. I've only shared the young to old model.
You can looks at the README of this repo, and follow the exact steps in the "training" section. At the end you will have both models and can use them however you wish

**Comment by Nithin-ML** [comment]
As you said i have trained and got two model inside checkpoints(epoch=99-step=237799.ckpt). And i extracted the 26 layers of weights of both genB2A for de-aging and  genA2B for aging and converted it into .pth file. But when i do the inference for both the aging and de-aging both are looking same almost only doing the aging not performing de-aging.

**Comment by HasnainRaz** [comment]
Hmm interesting.

I did notice that you have to have certain types of images to be able to see results. I would recommend the following:

Pick manually, an image of the oldest face you have in your dataset. Apply any preprocessing you did during training (normalization, resizing, center cropping etc) and then use the B2A model on this. If you get an image that looks de-aged, then we know the model is working.

After that, you can continue investigation which factors affect the de-aging (cropping, face size, image size etc)

**Comment by Nithin-ML** [comment]
I tried your approach with trained data but the results doesn't look like de-aged it mostly looked like  smoothing the faces. Please guide me if i need to do anymore tweaking to get the right de-aged one.
