### ISSUE TITLE
Other transformations

### ISSUE THREAD

**Issue by geopapyrus** [HasnainRaz/Fast-AgingGAN#4]
Hey!

 Thanks for sharing. 
 Can it be trained to make the person look younger instead of older?
 Can it also be trained for other transformations like make person smile? or remove/add beard/mustache etc?

thanks

**Comment by HasnainRaz** [comment]
Hey there,

Thanks for the feedback, yes it definitely can be trained to go younger from older, infact, we already do. The current training trains two generators, one that goes from young to old (A2B) and one that goes from old to young (B2A). I can share that model as well if it would help you.

As for your second question, you definitely can train this model to go from non-smile to smile, or beard to no beard etc, but you'd need a prepared dataset for this. Also, some of these might be easier to do with disentangled representations. If you really want to use unpaired image-to-image method like this repo, modern methods like U-GAT-IT might give you better results while being slower.

**Comment by geopapyrus** [comment]
Hey!

 Thanks for answering. Would love if you could share the older to younger model as well. I am currently training non simile to smile with CelebA dataset and I'll share my results with you.

thank you
