### ISSUE TITLE
Issues to run code in colab

### ISSUE THREAD

**Issue by Fatima-Ali8765** [HasnainRaz/Fast-AgingGAN#8]
Im trying to run your infer.py code on colab. I did so by copying line by line and pasting it on my notebook. I had to only change my file paths as I was working on colab. At first I struggled because it was giving me this error.

RuntimeError                              Traceback (most recent call last)
<ipython-input-19-94c1644cf597> in <module>()
     18   aged_face = (aged_face.squeeze().permute(1, 2, 0) + 1.0) / 2.0
     19   ax[0, i].imshow((img.squeeze().permute(1, 2, 0) + 1.0) / 2.0)
---> 20   ax[1, i].imshow(aged_face)
     21 plt.show()

6 frames
/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5624                               resample=resample, **kwargs)
   5625 
-> 5626         im.set_data(X)
   5627         im.set_alpha(alpha)
   5628         if im.get_clip_path() is None:

/usr/local/lib/python3.7/dist-packages/matplotlib/image.py in set_data(self, A)
    687             if isinstance(A, Image.Image):
    688                 A = pil_to_array(A)  # Needed e.g. to apply png palette.
--> 689         self._A = cbook.safe_masked_invalid(A, copy=True)
    690 
    691         if (self._A.dtype != np.uint8 and

/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/__init__.py in safe_masked_invalid(x, copy)
    704 
    705 def safe_masked_invalid(x, copy=False):
--> 706     x = np.array(x, subok=True, copy=copy)
    707     if not x.dtype.isnative:
    708         # Note that the argument to `byteswap` is 'inplace',

/usr/local/lib/python3.7/dist-packages/torch/tensor.py in __array__(self, dtype)
    619             return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
    620         if dtype is None:
--> 621             return self.numpy()
    622         else:
    623             return self.numpy().astype(dtype, copy=False)

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

I then tried to change the lines as follows:
aged_face = (aged_face.squeeze().permute(1, 2, 0).detach().numpy() + 1.0) / 2.0
 ax[0, i].imshow((img.squeeze().permute(1, 2, 0).detach().numpy() + 1.0) / 2.0)

but after doing, i was able to run the line but no output came from it.
So if possible, can you give me a full detailed guide on how do I run your infer.py on colab?
I would really really appreciate the help.
Your response would be acknowleged.

**Comment by HasnainRaz** [comment]
I think you had to invoke the "detach()" method because you got rid of the of "no_grad()" decorator on line 16 in infer.py.

To get the plots to display, you have to invoke "plt.show()". Otherwise the plot is not rendered. Please make sure you have this command at the end of your code (after plotting with ax[].imshow())
