### ISSUE TITLE
Age as parameter 

### ISSUE THREAD

**Issue by trippyml** [HasnainRaz/Fast-AgingGAN#9]
Is there any way to tweak the config to try and get age as a parameter? For example, if I wanted someone 20-30ish, 30-40ish, 40-50, etc. The output looks great so far, but would love to be able to have more fine grained control of the aging appearance

**Comment by HasnainRaz** [comment]
That's a good question. As a byproduct of the way this GAN is trained, there is no way currently to generate images based on age conditionality. You could however have a look at the cGANs and try to add the condition for age yourself. I imagine it can be done easily.
